

<section class="home">

    <!--SECTION 1 --------------------------------------------------------------->
    <article class="leader">

        <div style="position:relative; height:400px">
            <div style="position:absolute;z-index:1">
                <img src="img/image-interactive.jpg" alt="image VR Helmet" class="vr">
            </div>

            <div class="leader-text">
                <h3>The leader in interactive VR</h3>
                <p> Founded in 2011, Loopstudios has been producing world-class virtual reality projects for some of the best companies around the globe. Our award-winning creations have transformed businesses through digital experiences that bind to their brand</p>
            </div>
        </div>

    </article>

    <!--SECTION 2--------------------------------------------------------------->
    <article>

        <div class="creation">

            <h3>OUR CREATIONS</h3>

            <a href="#" alt="click" class="see">SEE ALL</a>

        </div>

        <div class="images">

            <div class="content">
                <a href="#"><img src="img/image-deep-earth.jpg" alt="image" class="img1"></a>
                <div class="text-center">DEEP EARTH</div>
            </div>

            <div class="content">
                <a href="#"><img src="img/image-night-arcade.jpg" alt="image" class="img2"></a>
                <div class="text-center">NIGHT ARCADE</div>
            </div>

            <div class="content">
                <a href="#"><img src="img/image-soccer-team.jpg" alt="image" class="img3"></a>
                <div class="text-center">SOCCER TEAM</div>
            </div>

            <div class="content">
                <a href="#"><img src="img/image-grid.jpg" alt="image" class="img4"></a>
                <div class="text-center">THE GRID</div>
            </div>

            <div class="content">
                <a href="#"><img src="img/image-from-above.jpg" alt="image" class="img5"></a>
                <div class="text-center">FROM UP ABOVE VR</div>
            </div>

            <div class="content">
                <a href="#"><img src="img/image-pocket-borealis.jpg" alt="image" class="img6"></a>
                <div class="text-center">POCKET BOREALIS</div>
            </div>

            <div class="content">
                <a href="#"><img src="img/image-curiosity.jpg" alt="image" class="img7"></a>
                <div class="text-center">THE CURIOSITY</div>
            </div>

            <div class="content">
                <a href="#"><img src="img/image-fisheye.jpg" alt="image" class="img8"></a>
                <div class="text-center">MAKE IT FISH EYE</div>
            </div>

            <a href="#" alt="click" class="see2">SEE ALL</a>

        </div>

    </article>

</section>
