<!doctype html>
<html lang="fr">
<head>
    <title>Leonard Palier - test Leeroy</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link rel="stylesheet" href="css/style.css">
    <link href="https://fonts.googleapis.com/css2?family=Alata&family=Josefin+Sans:wght@300&display=swap" rel="stylesheet">
</head>

<body>

<div class="site-container">

        <header class="header">

            <div class="navigation">
                <h1>Loopstudios</h1>

                <nav class="menu navbar">
                    <ul class="nav-menu">

                        <li class="nav-item">
                            <a href="index.php" class="nav-link underline">About</a>
                        </li>

                        <li class="nav-item">
                            <a href="#" class="nav-link underline">Careers</a>
                        </li>

                        <li class="nav-item">
                            <a href="#" class="nav-link underline">Events</a>
                        </li>

                        <li class="nav-item">
                            <a href="#" class="nav-link underline">Products</a>
                        </li>

                        <li class="nav-item">
                            <a href="#" class="nav-link underline">Support</a>
                        </li>

                    </ul>

                </nav>

                <div class="hamburger">
                    <span class="bar"></span>
                    <span class="bar"></span>
                    <span class="bar"></span>
                </div>

            </div>

            <h2>IMMERSIVE <br>EXPERIENCES<br> THAT DELIVER</h2>

        </header>

        <div class="site_content">

            <main class="container">

                <?php include $template ?>

            </main>

        </div>

</div>

<footer>

    <div class="navigation-footer">
        <p class="p1">Loopstudios</p>
        <div class="navigation-icons">
            <a href="#" class="underline"><img src="img/icon-facebook.svg" alt=""></a>
            <a href="#" class="underline"><img src="img/icon-twitter.svg" alt=""></a>
            <a href="#" class="underline"><img src="img/icon-pinterest.svg" alt=""></a>
            <a href="#" class="underline"><img src="img/icon-instagram.svg" alt=""></a>
        </div>

    </div>

    <div class="navigation-menu">
        <nav class="menu-footer">

                <a href="index.php" class="underline">About</a>

                <a href="#" class="underline">Careers</a>

                <a href="#" class="underline">Events</a>

                <a href="#" class="underline">Products</a>

                <a href="#" class="underline">Support</a>

        </nav>
        <p>© 2021 Loopstudios. All rigths reserved</p>
    </div>
</footer>

<script src="js/script.js"></script>

</body>

</html>
